<a href="https://colab.research.google.com/github/keithferns98/DeepLearning/blob/main/Tensorflow_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
print(tf.__version__)

2.5.0


In [ ]:
scaler=tf.constant(1)

In [ ]:
scaler

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [ ]:
scaler.ndim

0

In [ ]:
vector=tf.constant([1,2])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
matrix=tf.constant([[1,2,3],
                    [2,3,4]])

In [ ]:
matrix.ndim

2

In [ ]:
tensor=tf.constant([[[1,2,3],
                     [3,4,5]],
                    [[5,6,7],
                     [7,8,9]],
                     [[9,10,11],
                      [11,12,13]]])

In [ ]:
tf.constant([[[1,2,3],
              [2,3,4]],
             [[2,5,6],
              [4,3,1]],
             [[9,8,7],
              [2,3,8]]])

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [2, 3, 4]],

       [[2, 5, 6],
        [4, 3, 1]],

       [[9, 8, 7],
        [2, 3, 8]]], dtype=int32)>

In [ ]:
tensor.ndim

3

In [ ]:
unchangeable_tensor=tf.constant([5,5,5])
changeable_tensor=tf.Variable([6,6,6])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(3,) dtype=int32, numpy=array([6, 6, 6], dtype=int32)>,
 <tf.Tensor: shape=(3,), dtype=int32, numpy=array([5, 5, 5], dtype=int32)>)

In [ ]:
unchangeable_tensor[0].assign(7)

AttributeError: ignored

In [ ]:
changeable_tensor[0].assign(9)

<tf.Variable 'UnreadVariable' shape=(3,) dtype=int32, numpy=array([9, 6, 6], dtype=int32)>

In [ ]:
not_shuffled=tf.constant([[1,2,3],
                          [8,7,9],
                          [9,5,6,]])

In [ ]:
not_shuffled.ndim

2

In [ ]:
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[9, 5, 6],
       [1, 2, 3],
       [8, 7, 9]], dtype=int32)>

In [ ]:
tf.random.shuffle(90)
tf.random.shuffle(not_shuffled,seed=90)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[9, 5, 6],
       [8, 7, 9],
       [1, 2, 3]], dtype=int32)>

In [ ]:
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
tf.zeros(shape=(3,3))

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [ ]:
import numpy as np
na=np.arange(1,25,dtype=np.int32)

In [ ]:
na

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
t=tf.constant(na,shape=(2,3,4))

In [ ]:
t.ndim

3

In [ ]:
t

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int32)>

In [ ]:
tensor_4dim=tf.zeros(shape=[2,3,4,5])

In [ ]:
tensor_4dim

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
tensor_4dim.ndim

4

In [ ]:
tensor_4dim[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
tensor_4dim.shape,tf.size(tensor_4dim)

(TensorShape([2, 3, 4, 5]), <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
print("Datatype of every element:",tensor_4dim.dtype)
print("Number of dimension(rank):",tensor_4dim.ndim)
print("Shape of tensor",tensor_4dim.shape)
print("Elements along 0 axis ",tensor_4dim[0])
print("Elements along the last axis",tensor_4dim.shape[-1])
print("Elements along the last axis",tensor_4dim[-1])
print("Total number of elements in our tensor:",tf.size(tensor_4dim))

Datatype of every element: <dtype: 'float32'>
Number of dimension(rank): 4
Shape of tensor (2, 3, 4, 5)
Elements along 0 axis  tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 4, 5), dtype=float32)
Elements along the last axis 5
Elements along the last axis tf.Tensor(
[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]], shape=(3, 4, 5), dtype=float32)
Total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)


In [ ]:
tensor_4dim[:,:1,:1,:1]

<tf.Tensor: shape=(2, 1, 1, 1), dtype=float32, numpy=
array([[[[0.]]],


       [[[0.]]]], dtype=float32)>

In [ ]:
rank2_tensor=tf.constant([[110,5],
                          [7,9]])

In [ ]:
rank2_tensor.shape,rank2_tensor.ndim

(TensorShape([2, 2]), 2)

In [ ]:
rank2_tensor[:,-1].numpy()

array([5, 9], dtype=int32)

In [ ]:
# Add an extra dimension (to the end)
rank3_tensor=rank2_tensor[...,tf.newaxis]
rank3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[110],
        [  5]],

       [[  7],
        [  9]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank2_tensor,axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[110,   5]],

       [[  7,   9]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank2_tensor,axis=2)

In [ ]:
tf.expand_dims(rank)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[110,   5],
        [  7,   9]]], dtype=int32)>