<a href="https://colab.research.google.com/github/keithferns98/DeepLearning/blob/main/Tfbasics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
const=tf.constant(43)

In [ ]:
const

<tf.Tensor: shape=(), dtype=int32, numpy=43>

In [ ]:
const.shape

TensorShape([])

In [ ]:
const.numpy()

43

In [ ]:
const=tf.constant(43,dtype=float)

In [ ]:
const

<tf.Tensor: shape=(), dtype=float32, numpy=43.0>

In [ ]:
const_mat=tf.constant([[4,2],[3,5]])

In [ ]:
const_mat

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[4, 2],
       [3, 5]], dtype=int32)>

In [ ]:
const_mat.shape

TensorShape([2, 2])

In [ ]:
const_mat.shape

TensorShape([2, 2])

In [ ]:
const_mat.dtype

tf.int32

In [ ]:
tf.ones(shape=(2,3))*5

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[5., 5., 5.],
       [5., 5., 5.]], dtype=float32)>

In [ ]:
tf.zeros(shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

In [ ]:
const1=tf.constant([[11,22,33],[3,4,5]])
const2=tf.constant([[7,9,5],[3,4,5]])

In [ ]:
const1+const2

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[18, 31, 38],
       [ 6,  8, 10]], dtype=int32)>

In [ ]:
tf.add(const1,const2)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[18, 31, 38],
       [ 6,  8, 10]], dtype=int32)>

In [ ]:
X=tf.random.normal(shape=(2,3),mean=0,stddev=1)

In [ ]:
X

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[-0.19634494,  0.7826794 , -0.35831624],
       [ 1.0085917 , -1.2473623 , -0.669345  ]], dtype=float32)>

In [ ]:
X=tf.random.uniform(shape=(2,3),maxval=10,minval=0)

In [ ]:
X

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[8.871942 , 9.819616 , 0.3384769],
       [7.0093145, 6.5518703, 6.710782 ]], dtype=float32)>

In [ ]:
var1=tf.Variable(45)

In [ ]:
var1

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=45>

In [ ]:
var1=tf.Variable(45.4)

In [ ]:
var1

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=45.4>

In [ ]:
var1=4

In [ ]:
var1.assign(4)

AttributeError: ignored

In [ ]:
tensor=tf.Variable([[[10,11,12],[13,14,15]],[[10,11,12],[13,14,15]],[[10,11,12],[13,14,15]]])

In [ ]:
tensor

<tf.Variable 'Variable:0' shape=(3, 2, 3) dtype=int32, numpy=
array([[[10, 11, 12],
        [13, 14, 15]],

       [[10, 11, 12],
        [13, 14, 15]],

       [[10, 11, 12],
        [13, 14, 15]]], dtype=int32)>

In [ ]:
reshape=tf.reshape(tensor,[6,3])

In [ ]:
reshape

<tf.Tensor: shape=(6, 3), dtype=int32, numpy=
array([[10, 11, 12],
       [13, 14, 15],
       [10, 11, 12],
       [13, 14, 15],
       [10, 11, 12],
       [13, 14, 15]], dtype=int32)>

In [ ]:
reshape=tf.reshape(tensor,[1,18])

In [ ]:
reshape

<tf.Tensor: shape=(1, 18), dtype=int32, numpy=
array([[10, 11, 12, 13, 14, 15, 10, 11, 12, 13, 14, 15, 10, 11, 12, 13,
        14, 15]], dtype=int32)>

In [ ]:
tf.rank(tensor)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [ ]:
tensor[1][1][2]

<tf.Tensor: shape=(), dtype=int32, numpy=15>

In [ ]:
tensor[0,:,1:3]

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11, 12],
       [14, 15]], dtype=int32)>

In [ ]:
mat_u=tf.constant([[6,7,7]])
mat_v=tf.constant([[3,4,3]])

In [ ]:
mat_u*mat_v

<tf.Tensor: shape=(1, 3), dtype=int32, numpy=array([[18, 28, 21]], dtype=int32)>

In [ ]:
tf.matmul(tf.transpose(mat_u),mat_v)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[18, 24, 18],
       [21, 28, 21],
       [21, 28, 21]], dtype=int32)>

In [ ]:
ragged=tf.ragged.constant([[1,2,3,4,5],[],[1,2,3]])
ragged

<tf.RaggedTensor [[1, 2, 3, 4, 5], [], [1, 2, 3]]>

In [ ]:
ragged.shape

TensorShape([3, None])

In [ ]:
var1=[1,2,3,4,5]
var2=[1,2,4,4,5]
tf.math.squared_difference(var1,var2) #first negate and the squared 

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([0, 0, 1, 0, 0], dtype=int32)>

In [ ]:
num1=tf.constant([[1,2],[3,4]],dtype=tf.float32)
num1

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1., 2.],
       [3., 4.]], dtype=float32)>

In [ ]:
tf.reduce_mean(num1)#row mean

<tf.Tensor: shape=(), dtype=float32, numpy=2.5>

In [ ]:
tf.reduce_mean(num1,axis=1)#col mean

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.5, 3.5], dtype=float32)>